package engineindex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// fragmentMarker opens the generated .clangd file's first line. Its
// presence distinguishes a soft-ue-index-generated fragment (safe to
// rewrite, if the key still matches) from a hand-authored one (never
// touched). The key that follows it is what WriteFragment's conflict check
// compares against.
const fragmentMarker = "# soft-ue-index:generated-engine-index"

// FragmentPath is the project-local .clangd config fragment location for
// engineRoot. clangd discovers project-local config by walking up from
// each source file's own directory (confirmed by probe, not just docs);
// placing it at the engine root is the only placement that is an ancestor
// of every Engine/Plugins file without also being an ancestor of any
// project's own source tree on a different drive or subtree.
func FragmentPath(engineRoot string) string {
	return filepath.Join(engineRoot, ".clangd")
}

// WriteFragment writes (or updates) a .clangd fragment at engineRoot
// mounting idxAbsPath as a read-only external index for everything under
// "Engine/" (relative to engineRoot). clangd's PathMatch and MountPoint are
// both relative-to-the-fragment's-own-directory for a project-local
// fragment, not absolute -- confirmed by direct probe against clangd
// 20.1.8: an earlier absolute-path attempt compiled with no diagnostic but
// silently never matched anything, which reads identically to "the
// mechanism doesn't work" unless you check for it explicitly.
//
// Refuses to overwrite a file it did not write itself (no marker line) --
// remove or merge it manually first.
//
// ownerProjectID identifies which project last wrote this fragment, so a
// legitimate refresh (the SAME project, re-run after an engine hotfix or
// plugin update -- this package's own documented refresh workflow) is
// always allowed even though that changes the entry set and so Key's
// value, while a DIFFERENT project quietly repointing the shared fragment
// at its own, possibly narrower, index is refused unless the two happen to
// compute the same key (harmless: identical entry sets really do produce
// the same index). An earlier version of this function compared only the
// content key and treated every key change as a foreign-project conflict,
// which made the documented refresh workflow permanently refuse itself.
func WriteFragment(engineRoot, idxAbsPath, key, ownerProjectID string) error {
	path := FragmentPath(engineRoot)
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		existingKey, existingOwner, ok := parseFragmentMarker(string(existing))
		if !ok {
			return fmt.Errorf("%s already exists and was not generated by soft-ue-index -- remove or merge it manually before running index-engine", path)
		}
		if existingKey != key && existingOwner != ownerProjectID {
			return fmt.Errorf("%s is already configured for a different entry set by project %q (existing key %s, this run for project %q computed %s) -- likely a different project shares this engine root with a different Engine/Plugins module set; remove the existing fragment manually to replace it", path, existingOwner, existingKey, ownerProjectID, key)
		}
	case os.IsNotExist(err):
		// Nothing to conflict with.
	default:
		return err
	}
	content := fragmentContent(idxAbsPath, key, ownerProjectID)
	tmp := path + ".new"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func fragmentContent(idxAbsPath, key, ownerProjectID string) string {
	// File is single-quoted: index paths are absolute filesystem paths that
	// can legitimately contain '#' (which would otherwise truncate an
	// unquoted YAML plain scalar at a comment) and backslashes (which a
	// double-quoted scalar would interpret as escapes).
	return fragmentMarker + " " + key + " owner=" + ownerProjectID + "\n" +
		"If:\n" +
		"  PathMatch: \"Engine/.*\"\n" +
		"Index:\n" +
		"  External:\n" +
		"    File: '" + strings.ReplaceAll(idxAbsPath, "'", "''") + "'\n" +
		"    MountPoint: Engine\n"
}

// parseFragmentMarker reads the key and owning project ID back off a
// fragment this package generated (fragmentContent's first line). ok is
// false for anything else, including an empty or hand-authored file.
func parseFragmentMarker(content string) (key, owner string, ok bool) {
	line, _, _ := strings.Cut(content, "\n")
	prefix := fragmentMarker + " "
	if !strings.HasPrefix(line, prefix) {
		return "", "", false
	}
	rest := strings.TrimPrefix(line, prefix)
	key, ownerField, found := strings.Cut(rest, " owner=")
	if !found {
		return "", "", false
	}
	return strings.TrimSpace(key), strings.TrimSpace(ownerField), true
}
